[book]
authors = ["RM"]
language = "en"
multilingual = false
src = "src"
title = "財務金融"
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
[preprocessor.katex]
after = ["links"]

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding
[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter
[output.html.playground]
editable = false         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = false     # displays line numbers for editable code
runnable = true          # displays a run button for rust code


